### ISSUE TITLE
Can it support relative path and wildcard?

### ISSUE THREAD

**Issue by Freed-Wu** [oncomouse/coc-bibtex#5]
Such as 
```{.json}
{
	"list": {
		"source": {
			"bibtex": {
				"files": [
					"*.bib"
				]
			}
		}
	},
}
```
when i
```{.sh}
cd ~/Desktop/test/
vi main.md
```
the CWD is `~/Desktop/test/`.
i can see the bib source of `~/Desktop/test/main.bib`, `~/Desktop/test/test.bib`, etc.

Thanks! it is a good plugin. before i met it, i also want to try to realize it. thank you for your bring this plugin!

**Comment by oncomouse** [comment]
Yes, this should be in the plug-in and not too hard to implement. I'm in a crunch right now, but I'll get on this when I can.

**Comment by oncomouse** [comment]
This should be fixed in the new version (1.2.9)

**Comment by Freed-Wu** [comment]
Great!
and i have some question:
e.g.
```
{
	"list": {
		"source": {
			"bibtex": {
				"files": [
					"*.bib"
				]
			}
		}
	},
}
```

```{.shell}
cd ~/a_git_repo
vi main.bib
```
when enter vi, it will load bib source from `~/a_git_repo/*.bib`. it is right.

however,

```{.shell}
cd ~
vi ~/a_git_repo/main.md
```
when enter vi, `cd a_git_repo`, it will load bib source from not `~/a_git_repo/*.bib` but `~/*.bib`, user must `CocRestart` to update bib source.

Can bib source be updated automatically? thanks!

**Comment by oncomouse** [comment]
Ok, I added a listener for "DirChanged" events, which picks up changes and grabs new files when The directory changes. This should solve this problem.

**Comment by Freed-Wu** [comment]
![image](https://user-images.githubusercontent.com/32936898/94009214-bdf4ff00-fdd6-11ea-8c76-02ae243335eb.png)

![image](https://user-images.githubusercontent.com/32936898/94009383-f694d880-fdd6-11ea-934b-833d28d0fddf.png)

when `:new` to enter a new buffer then `:quit` to return the markdown, it will echo some error about DirChanged...

**Comment by oncomouse** [comment]
Sorry for this. I encountered this error and thought I fixed it. I published a new version, with a more thorough fix, that doesn't give me the error when I follow the steps you take

**Comment by Freed-Wu** [comment]
```{.vim}
" File: $XDG_CONFIG_HOME/nvim/test.vim
" OS: linux v5.4.13
" Vi: nvim v0.4.3
" Py: cpython v3.6.10
" Term: guake v3.7.0
set runtimepath=$VIMRUNTIME,$GITHUBWORKSPACE/neoclide/coc.nvim
" vi -u $XDG_CONFIG_HOME/nvim/test.vim
```

![a](https://user-images.githubusercontent.com/32936898/94017176-b2f39c00-fde1-11ea-93fe-7812bfc3aa59.png)
![Screenshot from 2020-09-23 21-00-56](https://user-images.githubusercontent.com/32936898/94017182-b5ee8c80-fde1-11ea-9d4d-90beb6fd8556.png)

**Comment by Freed-Wu** [comment]
`git init test` is necessary.

**Comment by oncomouse** [comment]
I just ran those exact steps and didn't get an error. Have you run `:CocUpdate` to make sure you have the 1.2.12 version of the extension? You can check with `:CocList extensions` and see the version:

![Screen Shot 2020-09-23 at 10 20 16 AM](https://user-images.githubusercontent.com/2666761/94033560-b574d800-fd86-11ea-98ac-e6445d3b0529.png)

If it isn't an outdated extension, there could be something else wrong with `coc-settings.json`.

For the record, since my setup is a bit different from yours, this was the `test.vim` I used. I'm not sure if it makes a difference:

~~~
set runtimepath=$VIMRUNTIME,~/.vim/plugged/desktop/coc.nvim
let g:coc_config_home = expand('~/dotfiles/vim/lsp-settings/coc.nvim/')
let g:coc_global_extensions = ['coc-bibtex']
~~~

**Comment by Freed-Wu** [comment]
Sorry! my network is not stable so i mistakenly thought i have updated....
